version: '3'

services:
    node:
        build: ./node
        environment:
          - NODE_ENV=production
        volumes:
          - ./dbs:/home/persons-and-apartments/dbs
        ports:
          - 8080:8080
